# Makefile

.PHONY: all pyenv pipx poetry

all: pyenv pipx poetry

pyenv:
	@echo "Installing pyenv"
	./scripts/install_pyenv.sh

pipx:
	@echo "Installing pipx"
	./scripts/install_pipx.sh

poetry:
	@echo "Installing poetry"
	./scripts/install_poetry.sh
